check __init__ and setuppy

diff --git a/.github/workflows/versioning.yml b/.github/workflows/versioning.yml
--- a/.github/workflows/versioning.yml
+++ b/.github/workflows/versioning.yml
@@ -33,20 +33,52 @@ jobs:
           if [[ -n "$CHANGED_FILES" ]]; then
             echo "------------------------------------------"
             echo "There are changes in the py3dinterpolations folder"
+            echo "------------------------------------------"
+            echo "Checking __init__.py file..."
 
-            head_version=$(git show HEAD:./py3dinterpolations/__init__.py | grep -oP '__version__ = "\K[^"]+')
-            echo "Head version: ${head_version}"
+            head_init_version=$(git show HEAD:./py3dinterpolations/__init__.py | grep -oP '__version__ = "\K[^"]+')
+            echo "Head version: ${head_init_version}"
 
-            base_version=$(git show ${BASE_SHA}:./py3dinterpolations/__init__.py | grep -oP '__version__ = "\K[^"]+')
-            echo "Base version: ${base_version}"
+            base_init_version=$(git show ${BASE_SHA}:./py3dinterpolations/__init__.py | grep -oP '__version__ = "\K[^"]+')
+            echo "Base version: ${base_init_version}"
 
-            if [ "$base_version" != "$head_version" ]; then
+            if [ "$base_init_version" != "$head_init_version" ]; then
               echo "The __version__ variable has been updated."
               exit 0
             else
               echo "Error: The __version__ variable has not been updated in package init."
               exit 1
             fi
+
+            echo "------------------------------------------"
+            echo "Checking setup.py file..."
+
+            head_setup_version=$(git show HEAD:./setup.py | grep -oP 'version="\K[^"]+')
+            echo "Head version: ${head_setup_version}"
+
+            base_setup_version=$(git show ${BASE_SHA}:./setup.py | grep -oP 'version="\K[^"]+')
+            echo "Base version: ${base_setup_version}"
+
+            if [ "$head_setup_version" == "$base_setup_version" ]; then
+              echo "The version variable have both been updated."
+              exit 0
+            else
+              echo "Error: The version variable has not been updated in setup.py."
+              exit 1
+            fi
+
+            echo "------------------------------------------"
+            echo "Checking they are equal..."
+
+            if [ "$head_init_version" == "$head_setup_version" ]; then
+              echo "The versions are equal."
+              exit 0
+            else
+              echo "Error: The versions are not equal."
+              exit 1
+            fi
+
+
           else
             echo "There are no changes in the py3dinterpolations folder"
             exit 0
